// Screen transition types (only edit if you add more) //
// MOVE TO screenTransition <<<<<<<<<<<<<<<<<<<<

// Instant transition / no transition animation //
#macro ST_NONE "NONE"

// Fade //
#macro ST_FADE "FADE"
#macro ST_FADE_SCREENSHOT_IN "FADE_SCREENSHOT_IN"
#macro ST_FADE_SPRITE "FADE_SPRITE"

// Scale //
#macro ST_TSCALE_X "TSCA_X"
#macro ST_TSCALE_X_SREENSHOT_IN "TSCA_X_SCREENSHOT_IN"
#macro ST_TSCALE_X_SPRITE "TSCA_X_SPRITE"
#macro ST_TSCALE_Y "TSCA_Y"
#macro ST_TSCALE_Y_SCREENSHOT_IN "TSCA_Y_SCREENSHOT_IN"
#macro ST_TSCALE_Y_SPRITE "TSCA_Y_SPRITE"
#macro ST_TSCALE_BOTH "TSCA_BOTH"
#macro ST_TSCALE_BOTH_SCREENSHOT_IN "TSCA_BOTH_SCREENSHOT_IN"
#macro ST_TSCALE_BOTH_SPRITE "TSCA_BOTH_SPRITE"

// Checkers //
#region Checker animation macros
	#region Horizontal
	// Right to left
	#macro ST_CHECKER_LR_X "CHKH_LR_X"
	#macro ST_CHECKER_LR_X_SCREENSHOT_IN "CHKH_LR_X_SCREENSHOT_IN"
	#macro ST_CHECKER_LR_X_SPRITE "CHKH_LR_X_SPRITE"
	#macro ST_CHECKER_LR_Y "CHKH_LR_Y"
	#macro ST_CHECKER_LR_Y_SCREENSHOT_IN "CHKH_LR_Y_SCREENSHOT_IN"
	#macro ST_CHECKER_LR_Y_SPRITE "CHKH_LR_Y_SPRITE"
	#macro ST_CHECKER_LR_BOTH "CHKH_LR_BOTH"
	#macro ST_CHECKER_LR_BOTH_SCREENSHOT_IN "CHKH_LR_BOTH_SCREENSHOT_IN"
	#macro ST_CHECKER_LR_BOTH_SPRITE "CHKH_LR_BOTH_SPRITE"
	// Left to right
	#macro ST_CHECKER_RL_X "CHKH_RL_X"
	#macro ST_CHECKER_RL_X_SCREENSHOT_IN "CHKH_RL_X_SCREENSHOT_IN"
	#macro ST_CHECKER_RL_X_SPRITE "CHKH_RL_X_SPRITE"
	#macro ST_CHECKER_RL_Y "CHKH_RL_Y"
	#macro ST_CHECKER_RL_Y_SCREENSHOT_IN "CHKH_RL_Y_SCREENSHOT_IN"
	#macro ST_CHECKER_RL_Y_SPRITE "CHKH_RL_Y_SPRITE"
	#macro ST_CHECKER_RL_BOTH "CHKH_RL_BOTH"
	#macro ST_CHECKER_RL_BOTH_SCREENSHOT_IN "CHKH_RL_BOTH_SCREENSHOT_IN"
	#macro ST_CHECKER_RL_BOTH_SPRITE "CHKH_RL_BOTH_SPRITE"
	#endregion
	#region Vertical
	// Up to down
	#macro ST_CHECKER_UD_X "CHKV_UD_X"
	#macro ST_CHECKER_UD_X_SCREENSHOT_IN "CHKV_UD_X_SCREENSHOT_IN"
	#macro ST_CHECKER_UD_X_SPRITE "CHKV_UD_X_SPRITE"
	#macro ST_CHECKER_UD_Y "CHKV_UD_Y"
	#macro ST_CHECKER_UD_Y_SCREENSHOT_IN "CHKV_UD_Y_SCREENSHOT_IN"
	#macro ST_CHECKER_UD_Y_SPRITE "CHKV_UD_Y_SPRITE"
	#macro ST_CHECKER_UD_BOTH "CHKV_UD_BOTH"
	#macro ST_CHECKER_UD_BOTH_SCREENSHOT_IN "CHKV_UD_BOTH_SCREENSHOT_IN"
	#macro ST_CHECKER_UD_BOTH_SPRITE "CHKV_UD_BOTH_SPRITE"
	// Down to up
	#macro ST_CHECKER_DU_X "CHKV_DU_X"
	#macro ST_CHECKER_DU_X_SCREENSHOT_IN "CHKV_DU_X_SCREENSHOT_IN"
	#macro ST_CHECKER_DU_X_SPRITE "CHKV_DU_X_SPRITE"
	#macro ST_CHECKER_DU_Y "CHKV_DU_Y"
	#macro ST_CHECKER_DU_Y_SCREENSHOT_IN "CHKV_DU_Y_SCREENSHOT_IN"
	#macro ST_CHECKER_DU_Y_SPRITE "CHKV_DU_Y_SPRITE"
	#macro ST_CHECKER_DU_BOTH "CHKV_DU_BOTH"
	#macro ST_CHECKER_DU_BOTH_SCREENSHOT_IN "CHKV_DU_BOTH_SCREENSHOT_IN"
	#macro ST_CHECKER_DU_BOTH_SPRITE "CHKV_DU_BOTH_SPRITE"
	#endregion
	#region Diagonal
	// Diagonal, up left to down right
	#macro ST_CHECKER_DIAG_UL_TO_DR_X "CHKD_UL_TO_DR_X"
	#macro ST_CHECKER_DIAG_UL_TO_DR_X_SCREENSHOT_IN "CHKD_UL_TO_DR_X_SCREENSHOT_IN"
	#macro ST_CHECKER_DIAG_UL_TO_DR_X_SPRITE "CHKD_UL_TO_DR_X_SPRITE"
	#macro ST_CHECKER_DIAG_UL_TO_DR_Y "CHKD_UL_TO_DR_Y"
	#macro ST_CHECKER_DIAG_UL_TO_DR_Y_SCREENSHOT_IN "CHKD_UL_TO_DR_Y_SCREENSHOT_IN"
	#macro ST_CHECKER_DIAG_UL_TO_DR_Y_SPRITE "CHKD_UL_TO_DR_Y_SPRITE"
	#macro ST_CHECKER_DIAG_UL_TO_DR_BOTH "CHKD_UL_TO_DR_BOTH"
	#macro ST_CHECKER_DIAG_UL_TO_DR_BOTH_SCREENSHOT_IN "CHKD_UL_TO_DR_BOTH_SCREENSHOT_IN"
	#macro ST_CHECKER_DIAG_UL_TO_DR_BOTH_SPRITE "CHKD_UL_TO_DR_BOTH_SPRITE"
	// Diagonal, up right to down left
	#macro ST_CHECKER_DIAG_UR_TO_DL_X "CHKD_UR_TO_DL_X"
	#macro ST_CHECKER_DIAG_UR_TO_DL_X_SCREENSHOT_IN "CHKD_UR_TO_DL_X_SCREENSHOT_IN"
	#macro ST_CHECKER_DIAG_UR_TO_DL_X_SPRITE "CHKD_UR_TO_DL_X_SPRITE"
	#macro ST_CHECKER_DIAG_UR_TO_DL_Y "CHKD_UR_TO_DL_Y"
	#macro ST_CHECKER_DIAG_UR_TO_DL_Y_SCREENSHOT_IN "CHKD_UR_TO_DL_Y_SCREENSHOT_IN"
	#macro ST_CHECKER_DIAG_UR_TO_DL_Y_SPRITE "CHKD_UR_TO_DL_Y_SPRITE"
	#macro ST_CHECKER_DIAG_UR_TO_DL_BOTH "CHKD_UR_TO_DL_BOTH"
	#macro ST_CHECKER_DIAG_UR_TO_DL_BOTH_SCREENSHOT_IN "CHKD_UR_TO_DL_BOTH_SCREENSHOT_IN"
	#macro ST_CHECKER_DIAG_UR_TO_DL_BOTH_SPRITE "CHKD_UR_TO_DL_BOTH_SPRITE"
	// Diagonal, down left to up right
	#macro ST_CHECKER_DIAG_DL_TO_UR_X "CHKD_DL_TO_UR_X"
	#macro ST_CHECKER_DIAG_DL_TO_UR_X_SCREENSHOT_IN "CHKD_DL_TO_UR_X_SCREENSHOT_IN"
	#macro ST_CHECKER_DIAG_DL_TO_UR_X_SPRITE "CHKD_DL_TO_UR_X_SPRITE"
	#macro ST_CHECKER_DIAG_DL_TO_UR_Y "CHKD_DL_TO_UR_Y"
	#macro ST_CHECKER_DIAG_DL_TO_UR_Y_SCREENSHOT_IN "CHKD_DL_TO_UR_Y_SCREENSHOT_IN"
	#macro ST_CHECKER_DIAG_DL_TO_UR_Y_SPRITE "CHKD_DL_TO_UR_Y_SPRITE"
	#macro ST_CHECKER_DIAG_DL_TO_UR_BOTH "CHKD_DL_TO_UR_BOTH"
	#macro ST_CHECKER_DIAG_DL_TO_UR_BOTH_SCREENSHOT_IN "CHKD_DL_TO_UR_BOTH_SCREENSHOT_IN"
	#macro ST_CHECKER_DIAG_DL_TO_UR_BOTH_SPRITE "CHKD_DL_TO_UR_BOTH_SPRITE"
	// Diagonal, down right to up left
	#macro ST_CHECKER_DIAG_DR_TO_UL_X "CHKD_DR_TO_UL_X"
	#macro ST_CHECKER_DIAG_DR_TO_UL_X_SCREENSHOT_IN "CHKD_DR_TO_UL_X_SCREENSHOT_IN"
	#macro ST_CHECKER_DIAG_DR_TO_UL_X_SPRITE "CHKD_DR_TO_UL_X_SPRITE"
	#macro ST_CHECKER_DIAG_DR_TO_UL_Y "CHKD_DR_TO_UL_Y"
	#macro ST_CHECKER_DIAG_DR_TO_UL_Y_SCREENSHOT_IN "CHKD_DR_TO_UL_Y_SCREENSHOT_IN"
	#macro ST_CHECKER_DIAG_DR_TO_UL_Y_SPRITE "CHKD_DR_TO_UL_Y_SPRITE"
	#macro ST_CHECKER_DIAG_DR_TO_UL_BOTH "CHKD_DR_TO_UL_BOTH"
	#macro ST_CHECKER_DIAG_DR_TO_UL_BOTH_SCREENSHOT_IN "CHKD_DR_TO_UL_BOTH_SCREENSHOT_IN"
	#macro ST_CHECKER_DIAG_DR_TO_UL_BOTH_SPRITE "CHKD_DR_TO_UL_BOTH_SPRITE"
	#endregion
	#region Spiral
	//#macro ST_CHECKER_SPIRAL_X "CHKS_SPIRAL_X"
	#endregion
#endregion

/*
// (TO DO) //
//spiral checkers
Screen move -- Will move from direction in to center. 
	will move image toward a direction in to center of screen, 
		find loc with circle line cast with spawn at loc outside of bounds.
speed 20 (do like transform with % of screen)
accel 0
fade t/f
rotate 0